let body = document.querySelector("body")
body.style.backgroundImage = "url('imagenes/cielo.jpg')"
body.style.backgroundAttachment = "fixed"
body.style.backgroundSize = "100% 100%"

let cripto = document.getElementById("cripto")
cripto.style.backgroundColor = "salmon"
cripto.style.fontFamily = "arial black"
cripto.style.borderRadius = "20px"
cripto.style.color = "black"
cripto.style.fontSize = "50px"